---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
   type: proxy
spec:
  replicas: 160
  selector:
    matchLabels:
      type: proxy
  template:
    metadata:
      labels:
        type: proxy
    spec:
     containers:
       - name: mynginx
         image: nginx
     affinity:
       nodeAffinity:
         requiredDuringSchedulingIgnoredDuringExecution:
           nodeSelectorTerms:
            - matchExpressions:
               - key: slave1
                 operator: In
                 values:
                  - intelliqit1
...








 
 
