---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
   type: proxy
spec:
  containers:
   - name: mynginx
     image: nginx
     resources:
       requests:
         cpu: "64m"
         memory: "100Mi"
       limits:
         cpu: "128m"
         memory: "200Mi"
