---
apiVersion: v1
kind: Namespace
metadata:
  name: my-namespace
---
apiVersion: v1
kind: Pod
metadata:
  name: httpd-pod
  namespace: my-namespace
  labels:
    type: webserver
spec:
  containers:
    - name: myhttpd
      image: httpd
...
