---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
   app: mysql
spec:
  clusterIP: None
  ports:
   - port: 3306
     name: tcp
     protocol: TCP
  selector:
    app: mysql
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-statefulset
  labels:
   app: mysql
spec:
  replicas: 2
  serviceName: mysql
  selector:
   matchLabels:
     app: mysql
  template:
    metadata:
      name: mysql-pod
      labels:
        app: mysql
    spec:
      containers:
        - name: mydb
          image: mysql
          ports:
            - containerPort: 3306
          env:
           - name: MYSQL_ROOT_PASSWORD
             value: intelliqit
          volumeMounts:
           - name: mysql-volume
             mountPath: /var/lib/mysql
      volumes:
        - name: mysql-volume
          persistentVolumeClaim:
           claimName: my-pvc


...
