---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer-deployment
  labels:
   type: db-client
spec:
  replicas: 1
  selector:
   matchLabels:
     type: db-client
  template:
    metadata:
      labels:
        type: db-client
    spec:
     containers:
      - name: myadminer
        image: adminer
        env:
          - name: ADMINER_DEFAULT_SERVER
            value: mysql
...
